spring:
  application:
    name: rpc-rabbitmq-client
#  rabbitmq:
#    listener:
#      simple:
#        default-requeue-rejected: true
logging:
  level:
    com.dchavez: DEBUG
    org.springframework.web: WARN
server:
  port: 8084
opentracing:
  jaeger:
    udp-sender:
      host: localhost
      port: 6831
  

